variables:
  - &rust 'rust:1.66.0-bullseye'
  - &buildx_plugin 'woodpeckerci/plugin-docker-buildx:2.1.0'

matrix:
  include:
    - DOCKERFILE: Dockerfile.multiarch
      AUTO_TAG_SUFFIX: ""
    - DOCKERFILE: Dockerfile.distroless.multiarch
      AUTO_TAG_SUFFIX: "-distroless"

pipeline:
  build-x86:
    image: *rust
    commands: 
      - export CARGO_HOME=$(pwd)/.cargo/
      - cargo test
      - cargo build --release
      - mkdir -p target/linux/amd64
      - cp target/release/picus target/linux/amd64/picus
    when:
      matrix:
        DOCKERFILE: Dockerfile.multiarch
    
  build-arm64:
    image: *rust
    commands: 
      - dpkg --add-architecture arm64
      - apt-get update
      - export DEBIAN_FRONTED=noninteractive
      - apt-get -y install --no-install-recommends gcc-aarch64-linux-gnu libssl-dev:arm64 libc6-dev:arm64
      - rustup target add aarch64-unknown-linux-gnu
      - export CARGO_HOME=$(pwd)/.cargo/
      - RUSTFLAGS="-C linker=aarch64-linux-gnu-gcc" PKG_CONFIG_SYSROOT_DIR=/ cargo build --target aarch64-unknown-linux-gnu --release
      - mkdir -p target/linux/arm64
      - cp target/aarch64-unknown-linux-gnu/release/picus target/linux/arm64/
    when:
      matrix:
        DOCKERFILE: Dockerfile.multiarch

  publish:
    image: *buildx_plugin
    settings:
      platforms: linux/amd64,linux/arm64
      repo: windsource/picus,ghcr.io/windsource/picus
      auto_tag: true
      auto_tag_suffix: ${AUTO_TAG_SUFFIX}
      dockerfile: ${Dockerfile}
      # dry_run: true
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://ghcr.io
          username:
            from_secret: github_username
          password:
            from_secret: github_password
    when:
      event: [push, tag, manual]
      branch: main
