pipeline:
  docker:
    image: plugins/docker
    settings:
      repo: windsource/picus
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
