[package]
name = "picus"
description ="Dynamically creates agent for Woodpecker CI in the cloud"
version = "0.3.1"
edition = "2021"
license = "MIT"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
hcloud = "0.12.0"
async-trait = "0.1.57"
handlebars = "4.3.4"
go-parse-duration = "0.1"
env_logger = "0.10.0"
log = "0.4.17"

[dev-dependencies]
mockall = "0.11.2"
